backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "downloads"
    label: "Downloads"
    folder: "downloads"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "File", name: "file", widget: "file"}
      - {label: "Version", name: "version", widget: "string", required: false}
      - {label: "Changelog", name: "changelog", widget: "markdown", required: false}
      - {label: "System Requirements", name: "system_requirements", widget: "text", required: false}